{
 "title": "Clamd Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(clamd_up{job=\"$job\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "host",
    "query": {
     "query": "label_values(clamd_up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clamd Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clamd_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PoolsCount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamd_pool_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClamdQueue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamd_queue{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClamdStats",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "clamd_version{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "ClamdStats"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "clamd_threads_idle{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "clamd_threads_live{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "clamd_threads_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "clamd_memory_free_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "clamd_memory_heap_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "clamd_memory_mmap_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mmap"
    },
    {
     "expr": "clamd_memory_releasable_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "releasable"
    },
    {
     "expr": "clamd_memory_used_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "PoolsMemory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "clamd_memory_pools_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "clamd_memory_pools_used_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}